### ISSUE TITLE
Decode resources to streams instead of disk

### ISSUE THREAD

**Issue by oSumAtrIX** [revanced/Apktool#1]
If aapt allows to write or read from memory, the necessity for a cache on disk can be removed. Otherwise aapt has to be patched to allow that.

**Comment by Lucaskyy** [comment]
This is overly complex. We can use a temp dir on most operating systems and use the app home dir on Android.
If you think otherwise, please reopen and explain why you think we should do that and how we can justify the complexity behind this.
