### ISSUE TITLE
9patch decoder support for Android

### ISSUE THREAD

**Issue by oSumAtrIX** [revanced/Apktool#3]
Apktool uses `BufferedImage` to decode 9patch. The Android SDK does not support `BufferedImage`. For that reason a solution has to be created.

**Comment by kakathic** [comment]
> Apktool uses `BufferedImage` to decode 9patch. The Android SDK does not support `BufferedImage`. For that reason a solution has to be created.

Please add tmp because java in android doesn't support tmp

java -Djava.io.tmpdir="/tmp" -jar cli.jar

**Comment by kakathic** [comment]
And let's add command -p means framework/tmp it will help some java commands in android to run without termux app

**Comment by oSumAtrIX** [comment]
We do not use the /tmp directory.

**Comment by kakathic** [comment]
> We do not use the /tmp directory.

You can replace the tmp directory like the -t command of revanced-cli.jar

**Comment by kakathic** [comment]
It is important to have this command line: -Djava.io.tmpdir=

**Comment by kakathic** [comment]
> This is not required as previously said.

This is a bug of apktool because simply apktool they don't support for android device

**Comment by oSumAtrIX** [comment]
> This is a bug of apktool because simply apktool they don't support for android device

[Once again, this is not required](https://github.com/revanced/Apktool/issues/3#issuecomment-1169885271).

**Comment by anirudhmalik** [comment]
It can be solved using `bitmap`
Refer this for solution :
https://github.com/anirudhmalik/xhunter/blob/master/android/app/src/main/java/brut/androlib/res/decoder/Res9patchStreamDecoder.java

**Comment by oSumAtrIX** [comment]
Looks like exactly what we need! Thank you!

**Comment by TheJeterLP** [comment]
> It can be solved using `bitmap` Refer this for solution : https://github.com/anirudhmalik/xhunter/blob/master/android/app/src/main/java/brut/androlib/res/decoder/Res9patchStreamDecoder.java

You, my friend just made our day!

**Comment by Sculas** [comment]
Fixed in 820ef1e4cddc152f97bf6b60411a29f2ac5279af.

**Comment by Aunali321** [comment]
Thank you so much yaar! Exactly what we needed!
