### ISSUE TITLE
[FEAT] Remove prebuilt aapt binaries

### ISSUE THREAD

**Issue by Canny1913** [revanced/Apktool#5]
**Is your feature request related to a problem? Please describe.**
Apktool has prebuilt aapt binaries for compiling resources. Those are not used by ReVanced Manager and unnecessarily increases the total APK size.

**Describe the solution you'd like**
Remove prebuilt aapt binaries from source code (without breaking patcher) or find a way to not include binaries in manager.

**Comment by oSumAtrIX** [comment]
This is directly caused by apktool version controlling the binaries. The CLI needs them, while the mamager ships it's own binaries, ideally the CLI ships it's own too instead of apktools prebuild binaries.

**Comment by Canny1913** [comment]
> This is directly caused by apktool version controlling the binaries. The CLI needs them, while the mamager ships it's own binaries, ideally the CLI ships it's own too instead of apktools prebuild binaries.

Why not just use the patched builds in both.

**Comment by oSumAtrIX** [comment]
Android handles binaries differently than Java, they have to be shipped how Android specifies to, while for Java you can ship them via the resources.

**Comment by Canny1913** [comment]
Solved by manually excluding binaries in build script.
